<a href="https://colab.research.google.com/github/asepmuhidin/BD-DM-C01/blob/main/studi_kasus_data_nulll.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
ffile="https://raw.githubusercontent.com/asepmuhidin/BD-DM-C02/refs/heads/main/Tabel_Penjualan_Rupiah.csv"

dataset=pd.read_csv(ffile)
dataset.head()

,Transaction ID,Tanggal Transaksi,Nama Produk,Kategori,Jumlah,Harga (Rupiah),Total Harga (Rupiah)
0,101,01-01-2024,Laptop,Elektronik,1.0,"15,000,000","15,000,000"
1,102,02-01-2024,Smartphone,Elektronik,2.0,"12,000,000","24,000,000"
2,103,03-01-2024,Headset,Aksesori,NaN,"750,000",NaN
3,104,03-01-2024,Headset,Aksesori,1.0,"750,000","750,000"
4,105,07-01-2024,Mouse,Aksesori,3.0,NaN,NaN

In [4]:
dataset.isnull().sum()

Transaction ID          0
Tanggal Transaksi       0
Nama Produk             0
Kategori                0
Jumlah                  2
Harga (Rupiah)          1
Total Harga (Rupiah)    3
dtype: int64

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Transaction ID        10 non-null     int64
 1   Tanggal Transaksi     10 non-null     object
 2   Nama Produk           10 non-null     object
 3   Kategori              10 non-null     object
 4   Jumlah                8 non-null      float64
 5   Harga (Rupiah)        9 non-null      object
 6   Total Harga (Rupiah)  7 non-null      object
dtypes: float64(1), int64(1), object(5)
memory usage: 692.0+ bytes

In [10]:
dataset['Harga (Rupiah)'] = dataset['Harga (Rupiah)'].str.replace(',', '', regex=False).astype(float)

In [14]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Transaction ID        10 non-null     int64
 1   Tanggal Transaksi     10 non-null     object
 2   Nama Produk           10 non-null     object
 3   Kategori              10 non-null     object
 4   Jumlah                10 non-null     float64
 5   Harga (Rupiah)        10 non-null     float64
 6   Total Harga (Rupiah)  7 non-null      object
dtypes: float64(2), int64(1), object(4)
memory usage: 692.0+ bytes

In [11]:
dataset.fillna({
    'Jumlah':dataset['Jumlah'].mean(),
    'Harga (Rupiah)':dataset['Harga (Rupiah)'].mean(),
},inplace=True)

In [16]:
pd.set_option('display.float_format', '{:,.2f}'.format)
dataset['Total Harga (Rupiah)'] = dataset['Jumlah'] * dataset['Harga (Rupiah)']
dataset.head(10)

,Transaction ID,Tanggal Transaksi,Nama Produk,Kategori,Jumlah,Harga (Rupiah),Total Harga (Rupiah)
0,101,01-01-2024,Laptop,Elektronik,1.00,"15,000,000.00","15,000,000.00"
1,102,02-01-2024,Smartphone,Elektronik,2.00,"12,000,000.00","24,000,000.00"
2,103,03-01-2024,Headset,Aksesori,1.50,"750,000.00","1,125,000.00"
3,104,03-01-2024,Headset,Aksesori,1.00,"750,000.00","750,000.00"
4,105,07-01-2024,Mouse,Aksesori,3.00,"12,833,333.33","38,500,000.00"
5,106,04-01-2024,Keyboard,Aksesori,2.00,"1,500,000.00","3,000,000.00"
6,107,05-01-2024,Monitor,Elektronik,1.00,"45,000,000.00","45,000,000.00"
7,107,05-01-2024,Monitor,Elektronik,1.00,"45,000,000.00","45,000,000.00"
8,108,06-01-2024,Printer,Elektronik,1.50,"3,000,000.00","4,500,000.00"
9,109,07-01-2024,Tablet,Elektronik,1.00,"-7,500,000.00","-7,500,000.00"